Run_loot_table = {
-- {["loot_id"] = "", ["loot_name"] = "", ["prio"] = " Prio: tbd",},
--   Karazhan
-- Attumen the Huntsman
{["loot_id"] = "28509", ["loot_name"] = "Worgen Claw Necklace", ["prio"] = " Prio: Hunter, F Druid, Rogue, Enh Shaman",},
{["loot_id"] = "28507", ["loot_name"] = "Handwraps of Flowing Thought", ["prio"] = " Prio: Warlock, > Mage Tank, Boomkin, Ele Shaman",},
{["loot_id"] = "28508", ["loot_name"] = "Gloves of Saintly Blessings", ["prio"] = " Prio: H Priest",},
{["loot_id"] = "28477", ["loot_name"] = "Harbinger Bands", ["prio"] = " Prio: Warlock, Mage, S Priest",},
{["loot_id"] = "28504", ["loot_name"] = "Steelhawk Crossbow", ["prio"] = " Prio: Hunter",},
{["loot_id"] = "28506", ["loot_name"] = "Gloves of Dexterous Manipulation", ["prio"] = " Prio: Feral Dps",},
{["loot_id"] = "28453", ["loot_name"] = "Bracers of the White Stag", ["prio"] = " Prio: None",},
{["loot_id"] = "28454", ["loot_name"] = "Stalker's War Bands", ["prio"] = " Prio: Enh Shaman, Hunter",},
{["loot_id"] = "28503", ["loot_name"] = "Whirlwind Bracers", ["prio"] = " Prio: R Shaman",},
{["loot_id"] = "28505", ["loot_name"] = "Gauntlets of Renewed Hope", ["prio"] = " Prio: H Pally",},
{["loot_id"] = "28502", ["loot_name"] = "Vambraces of Courage", ["prio"] = " Prio: P Pally, T Warrior",},
{["loot_id"] = "28510", ["loot_name"] = "Spectral Band of Innervation", ["prio"] = " Prio: Caster",},
{["loot_id"] = "30480", ["loot_name"] = "Fiery Warhorse's Reins", ["prio"] = " Prio: None",},
-- Moroes
{["loot_id"] = "28530", ["loot_name"] = "Brooch of Unquenchable Fury", ["prio"] = " Prio: Casters",},
{["loot_id"] = "28529", ["loot_name"] = "Royal Cloak of Arathi Kings", ["prio"] = " Prio: D Warrior,  Ret Pally, Enh Shaman",},
{["loot_id"] = "28570", ["loot_name"] = "Shadow-Cloak of Dalaran", ["prio"] = " Prio: Caster",},
{["loot_id"] = "28565", ["loot_name"] = "Nethershard Girdle", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28524", ["loot_name"] = "Emerald Ripper", ["prio"] = " Prio: Dagger Rogues > Phy DPS",},
{["loot_id"] = "28545", ["loot_name"] = "Edgewalker Longboots", ["prio"] = " Prio: Hunter, Rogue,  F Druid",},
{["loot_id"] = "28567", ["loot_name"] = "Belt of Gale Force", ["prio"] = " Prio: R Shaman",},
{["loot_id"] = "28525", ["loot_name"] = "Signet of Unshakable Faith", ["prio"] = " Prio: H Priest, R Druid",},
{["loot_id"] = "28569", ["loot_name"] = "Boots of Valiance", ["prio"] = " Prio: H Pally",},
{["loot_id"] = "28566", ["loot_name"] = "Crimson Girdle of the Indomitable", ["prio"] = " Prio: Plate Tanks",},
{["loot_id"] = "28528", ["loot_name"] = "Moroes' Lucky Pocket Watch", ["prio"] = " Prio: T Druid > Tanks",},
-- Maiden of Virtue
{["loot_id"] = "28516", ["loot_name"] = "Barbed Choker of Discipline", ["prio"] = " Prio: Tanks",},
{["loot_id"] = "28517", ["loot_name"] = "Boots of Foretelling", ["prio"] = " Prio: Caster DPS (except S Priest)",},
{["loot_id"] = "28511", ["loot_name"] = "Bands of Indwelling", ["prio"] = " Prio: H Priest, R Druid",},
{["loot_id"] = "28515", ["loot_name"] = "Bands of Nefarious Deeds", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28521", ["loot_name"] = "Mitts of the Treemender", ["prio"] = " Prio: R Druid",},
{["loot_id"] = "28514", ["loot_name"] = "Bracers of Maliciousness", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28519", ["loot_name"] = "Gloves of Quickening", ["prio"] = " Prio: Enh Shaman, Hunter",},
{["loot_id"] = "28523", ["loot_name"] = "Totem of Healing Rains", ["prio"] = " Prio: R Shaman",},
{["loot_id"] = "28520", ["loot_name"] = "Gloves of Centering", ["prio"] = " Prio: R Shaman",},
{["loot_id"] = "28522", ["loot_name"] = "Shard of the Virtuous", ["prio"] = " Prio: R Shaman, H Pally",},
{["loot_id"] = "28518", ["loot_name"] = "Iron Gauntlets of the Maiden", ["prio"] = " Prio: P Warrior > Tanks",},
{["loot_id"] = "28512", ["loot_name"] = "Bracers of Justice", ["prio"] = " Prio: H Pally",},
-- Opera Event - Red Riding Hood
{["loot_id"] = "28582", ["loot_name"] = "Red Riding Hood's Cloak", ["prio"] = " Prio: Healers",},
{["loot_id"] = "28584", ["loot_name"] = "Big Bad Wolf's Paw", ["prio"] = " Prio: DE / Fist Rogue Crap",},
{["loot_id"] = "28581", ["loot_name"] = "Wolfslayer Sniper Rifle", ["prio"] = " Prio: Hunter",},
{["loot_id"] = "28583", ["loot_name"] = "Big Bad Wolf's Head", ["prio"] = " Prio: Ele Shaman",},
-- Opera Event - Romulo and Julianne
{["loot_id"] = "28578", ["loot_name"] = "Masquerade Gown", ["prio"] = " Prio: H Priest, R Druid",},
{["loot_id"] = "28572", ["loot_name"] = "Blade of the Unrequited", ["prio"] = " Prio: Dagger Rogue over dps",},
{["loot_id"] = "28579", ["loot_name"] = "Romulo's Poison Vial", ["prio"] = " Prio: Tanks = Physical Dps (not Pally tanks)",},
{["loot_id"] = "28573", ["loot_name"] = "Despair", ["prio"] = " Prio: 2H Dps",},
-- Opera Event - Wizard of Oz
{["loot_id"] = "28585", ["loot_name"] = "Ruby Slippers", ["prio"] = " Prio: Mage, Warlock, S Priest. Not if you have Boots of Foretelling",},
{["loot_id"] = "28586", ["loot_name"] = "Wicked Witch's Hat", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28587", ["loot_name"] = "Legacy", ["prio"] = " Prio: 2H DPS Mana ",},
{["loot_id"] = "28588", ["loot_name"] = "Blue Diamond Witchwand", ["prio"] = " Prio: H Priest",},
-- Opera Event - Shared Loot
{["loot_id"] = "28594", ["loot_name"] = "Trial-Fire Trousers", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28591", ["loot_name"] = "Earthsoul Leggings", ["prio"] = " Prio: R Druid",},
{["loot_id"] = "28589", ["loot_name"] = "Beastmaw Pauldrons", ["prio"] = " Prio: DE / (Hunter, Enh Shaman)",},
{["loot_id"] = "28593", ["loot_name"] = "Eternium Greathelm", ["prio"] = " Prio: DE / T Warrior",},
{["loot_id"] = "28590", ["loot_name"] = "Ribbon of Sacrifice", ["prio"] = " Prio: H Pally, R Shaman (Priest?)",},
{["loot_id"] = "28592", ["loot_name"] = "Libram of Souls Redeemed", ["prio"] = " Prio: H Pally",},
-- Curator
{["loot_id"] = "29756", ["loot_name"] = "Gloves of the Fallen Hero", ["prio"] = " Prio: Mage, Warlock > Hunter",},
{["loot_id"] = "29757", ["loot_name"] = "Gloves of the Fallen Champion", ["prio"] = " Prio: P Pally R Pally > everyone",},
{["loot_id"] = "29758", ["loot_name"] = "Gloves of the Fallen Defender", ["prio"] = " Prio: T Druid, > H Priest > everyone",},
{["loot_id"] = "28612", ["loot_name"] = "Pauldrons of the Solace-Giver", ["prio"] = " Prio: H Priest",},
{["loot_id"] = "28647", ["loot_name"] = "Forest Wind Shoulderpads", ["prio"] = " Prio: R Druid",},
{["loot_id"] = "28631", ["loot_name"] = "Dragon-Quake Shoulderguards", ["prio"] = " Prio: R Shaman",},
{["loot_id"] = "28621", ["loot_name"] = "Wrynn Dynasty Greaves", ["prio"] = " Prio: P Pally > T Warrior",},
{["loot_id"] = "28649", ["loot_name"] = "Garona's Signet Ring", ["prio"] = " Prio: Hunter, Rogue, Feral Druid",},
{["loot_id"] = "28633", ["loot_name"] = "Staff of Infinite Mysteries", ["prio"] = " Prio: Mage Tank > Caster",},
-- Shade of Aran
{["loot_id"] = "28674", ["loot_name"] = "Saberclaw Talisman", ["prio"] = " Prio: Agility DPS",},
{["loot_id"] = "28672", ["loot_name"] = "Drape of the Dark Reavers", ["prio"] = " Prio: Physcial DPS",},
{["loot_id"] = "28663", ["loot_name"] = "Boots of the Incorrupt", ["prio"] = " Prio: H Priest",},
{["loot_id"] = "28670", ["loot_name"] = "Boots of the Infernal Coven", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28726", ["loot_name"] = "Mantle of the Mind Flayer", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28669", ["loot_name"] = "Rapscallion Boots", ["prio"] = " Prio: Physcial DPS",},
{["loot_id"] = "28671", ["loot_name"] = "Steelspine Faceguard", ["prio"] = " Prio: Hunter, Enh Shaman, Ret Pally",},
{["loot_id"] = "28728", ["loot_name"] = "Aran's Soothing Sapphire", ["prio"] = " Prio: Healer",},
{["loot_id"] = "28666", ["loot_name"] = "Pauldrons of the Justice-Seeker", ["prio"] = " Prio: H Pally",},
{["loot_id"] = "28675", ["loot_name"] = "Shermanar Great-Ring", ["prio"] = " Prio: T Druid, > Tank",},
{["loot_id"] = "28727", ["loot_name"] = "Pendant of the Violet Eye", ["prio"] = " Prio: H Pally, R Shaman",},
{["loot_id"] = "28673", ["loot_name"] = "Tirisfal Wand of Ascendancy", ["prio"] = " Prio: Caster DPS",},
-- Terrestian Illhoof
{["loot_id"] = "28653", ["loot_name"] = "Shadowvine Cloak of Infusion", ["prio"] = " Prio: De / no one",},
{["loot_id"] = "28660", ["loot_name"] = "Gilded Thorium Cloak", ["prio"] = " Prio: T Druid",},
{["loot_id"] = "28652", ["loot_name"] = "Cincture of Will", ["prio"] = " Prio: H Priest",},
{["loot_id"] = "28654", ["loot_name"] = "Malefic Girdle", ["prio"] = " Prio: Caster DPS (Not S Priest)",},
{["loot_id"] = "28655", ["loot_name"] = "Cord of Nature's Sustenance", ["prio"] = " Prio: R Druid",},
{["loot_id"] = "28656", ["loot_name"] = "Girdle of the Prowler", ["prio"] = " Prio: Hunter, Enh Shaman",},
{["loot_id"] = "28657", ["loot_name"] = "Fool's Bane", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28662", ["loot_name"] = "Breastplate of the Lightbinder", ["prio"] = " Prio: H Pally",},
{["loot_id"] = "28661", ["loot_name"] = "Mender's Heart-Ring", ["prio"] = " Prio: H Priest, R Druid",},
{["loot_id"] = "28658", ["loot_name"] = "Terestian's Stranglestaff", ["prio"] = " Prio: Feral Druid, Tank & DPS",},
{["loot_id"] = "28785", ["loot_name"] = "The Lightning Capacitor", ["prio"] = " Prio: Ele Shaman",},
{["loot_id"] = "28659", ["loot_name"] = "Xavian Stiletto", ["prio"] = " Prio: Rogue, D Warrior",},
-- Prince Malchezaar
{["loot_id"] = "28762", ["loot_name"] = "Adornment of Stolen Souls", ["prio"] = " Prio: Caster DPS (Not S Priest)",},
{["loot_id"] = "29759", ["loot_name"] = "Helm of the Fallen Hero", ["prio"] = " Prio: Warlock > Mage  > Hunter",},
{["loot_id"] = "29760", ["loot_name"] = "Helm of the Fallen Champion", ["prio"] = " Prio: Equal Prio",},
{["loot_id"] = "29761", ["loot_name"] = "Helm of the Fallen Defender", ["prio"] = " Prio: Equal Prio unless you have tailoring",},
{["loot_id"] = "28772", ["loot_name"] = "Sunfury Bow of the Phoenix", ["prio"] = " Prio: Hunter",},
{["loot_id"] = "28764", ["loot_name"] = "Farstrider Wildercloak", ["prio"] = " Prio: Physical DPS / DE",},
{["loot_id"] = "28765", ["loot_name"] = "Stainless Cloak of the Pure Hearted", ["prio"] = " Prio: Healer",},
{["loot_id"] = "28766", ["loot_name"] = "Ruby Drape of the Mysticant", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28768", ["loot_name"] = "Malchazeen", ["prio"] = " Prio: Dagger Rogue >",},
{["loot_id"] = "28770", ["loot_name"] = "Nathrezim Mindblade", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28767", ["loot_name"] = "The Decapitator", ["prio"] = " Prio: Dual Wield Melee DPS",},
{["loot_id"] = "28771", ["loot_name"] = "Light's Justice", ["prio"] = " Prio: H Priest, R Druids",},
{["loot_id"] = "28757", ["loot_name"] = "Ring of a Thousand Marks", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28763", ["loot_name"] = "Jade Ring of the Everliving", ["prio"] = " Prio: H Pally, R Shaman",},
{["loot_id"] = "28773", ["loot_name"] = "Gorehowl", ["prio"] = " Prio: Ret Pally, 2H  Warrior",},
-- Netherspite
{["loot_id"] = "28731", ["loot_name"] = "Shining Chain of the Afterworld", ["prio"] = " Prio: H Priest, R Druid",},
{["loot_id"] = "28744", ["loot_name"] = "Uni-Mind Headdress", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28742", ["loot_name"] = "Pantaloons of Repentance", ["prio"] = " Prio: H Priest",},
{["loot_id"] = "28732", ["loot_name"] = "Cowl of Defiance", ["prio"] = " Prio: Agility Dps inc Enh Shaman",},
{["loot_id"] = "28741", ["loot_name"] = "Skulker's Greaves", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28735", ["loot_name"] = "Earthblood Chestguard", ["prio"] = " Prio: R Shaman",},
{["loot_id"] = "28740", ["loot_name"] = "Rip-Flayer Leggings", ["prio"] = " Prio: Physical Mana DPS",},
{["loot_id"] = "28734", ["loot_name"] = "Jewel of Infinite Possibilities", ["prio"] = " Prio: Caster DPS > Fire Mages",},
{["loot_id"] = "28729", ["loot_name"] = "Spiteblade", ["prio"] = " Prio: Rogue = Warrior",},
{["loot_id"] = "28743", ["loot_name"] = "Mantle of Abrahmis", ["prio"] = " Prio: Plate Tanks",},
{["loot_id"] = "28733", ["loot_name"] = "Girdle of Truth", ["prio"] = " Prio: H Pally",},
{["loot_id"] = "28730", ["loot_name"] = "Mithril Band of the Unscarred", ["prio"] = " Prio: Physical Strength Dps, Enh Shaman",},
-- Nightbane
{["loot_id"] = "28609", ["loot_name"] = "Emberspur Talisman", ["prio"] = " Prio: Healer",},
{["loot_id"] = "28602", ["loot_name"] = "Robe of the Elder Scribes", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28600", ["loot_name"] = "Stonebough Jerkin", ["prio"] = " Prio: R Druid",},
{["loot_id"] = "28601", ["loot_name"] = "Chestguard of the Conniver", ["prio"] = " Prio: Agility Dps Enh Shaman",},
{["loot_id"] = "28599", ["loot_name"] = "Scaled Breastplate of Carnage", ["prio"] = " Prio: Physical Mana DPS",},
{["loot_id"] = "28610", ["loot_name"] = "Ferocious Swift-Kickers", ["prio"] = " Prio: Physical Mana DPS",},
{["loot_id"] = "28603", ["loot_name"] = "Talisman of Nightbane", ["prio"] = " Prio: Enh Shaman > Caster Dps",},
{["loot_id"] = "28597", ["loot_name"] = "Panzar'Thar Breastplate", ["prio"] = " Prio: Plate Tank",},
{["loot_id"] = "28608", ["loot_name"] = "Ironstriders of Urgency", ["prio"] = " Prio: Plate DPS",},
{["loot_id"] = "28606", ["loot_name"] = "Shield of Impenetrable Darkness", ["prio"] = " Prio: Plate Tank",},
{["loot_id"] = "28611", ["loot_name"] = "Dragonheart Flameshield", ["prio"] = " Prio: Ele Shaman",},
{["loot_id"] = "28604", ["loot_name"] = "Nightstaff of the Everliving", ["prio"] = " Prio: H Priest, R Druid",},
-- Chess Event
{["loot_id"] = "28745", ["loot_name"] = "Mithril Chain of Heroism", ["prio"] = " Prio: Melee Agility DPS",},
{["loot_id"] = "28756", ["loot_name"] = "Headdress of the High Potentate", ["prio"] = " Prio: H Priest, R Druid",},
{["loot_id"] = "28752", ["loot_name"] = "Forestlord Striders", ["prio"] = " Prio: R Druid",},
{["loot_id"] = "28755", ["loot_name"] = "Bladed Shoulderpads of the Merciless", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28750", ["loot_name"] = "Girdle of Treachery", ["prio"] = " Prio: Agility DPS, Enh Shaman",},
{["loot_id"] = "28746", ["loot_name"] = "Fiend Slayer Boots", ["prio"] = " Prio: Hunter",},
{["loot_id"] = "28751", ["loot_name"] = "Heart-Flame Leggings", ["prio"] = " Prio: R Shaman",},
{["loot_id"] = "28749", ["loot_name"] = "King's Defender", ["prio"] = " Prio: P Warrior",},
{["loot_id"] = "28747", ["loot_name"] = "Battlescar Boots", ["prio"] = " Prio: Plate Tank",},
{["loot_id"] = "28748", ["loot_name"] = "Legplates of the Innocent", ["prio"] = " Prio: H Pally",},
{["loot_id"] = "28753", ["loot_name"] = "Ring of Recurrence", ["prio"] = " Prio: Caster DPS (except S Priest)",},
{["loot_id"] = "28754", ["loot_name"] = "Triptych Shield of the Ancients", ["prio"] = " Prio: R Shaman, H Pally",},
-- Trash
{["loot_id"] = "30642", ["loot_name"] = "Drape of the Righteous", ["prio"] = " Prio: Holy DPS Priest",},
{["loot_id"] = "30666", ["loot_name"] = "Ritssyn's Lost Pendant", ["prio"] = " Prio: S Priest = Affiction Warlock",},
{["loot_id"] = "30667", ["loot_name"] = "Ring of Unrelenting Storms", ["prio"] = " Prio: Ele Shaman",},
{["loot_id"] = "30668", ["loot_name"] = "Grasp of the Dead", ["prio"] = " Prio: Frost Mage",},
{["loot_id"] = "30673", ["loot_name"] = "Inferno Waist Cord", ["prio"] = " Prio: Fire Mage, Fire Warlock",},
{["loot_id"] = "30644", ["loot_name"] = "Grips of Deftness", ["prio"] = " Prio: Enh Shaman",},
{["loot_id"] = "30674", ["loot_name"] = "Zierhut's Lost Treads", ["prio"] = " Prio: T Druid > F Druid > Agility DPS",},
{["loot_id"] = "30643", ["loot_name"] = "Belt of the Tracker", ["prio"] = " Prio: DE",},
{["loot_id"] = "30641", ["loot_name"] = "Boots of Elusion", ["prio"] = " Prio: Plate Tank",},

--  Gruul's Lair
-- High King Maulgar
{["loot_id"] = "29764", ["loot_name"] = "Pauldrons of the Fallen Defender", ["prio"] = " Prio: None",},
{["loot_id"] = "29763", ["loot_name"] = "Pauldrons of the Fallen Champion", ["prio"] = " Prio: None",},
{["loot_id"] = "29762", ["loot_name"] = "Pauldrons of the Fallen Hero", ["prio"] = " Prio: Mage = Warlock > Hunter",},
{["loot_id"] = "28801", ["loot_name"] = "Maulgar's Warhelm", ["prio"] = " Prio: Enh Shammy, Ret Pally",},
{["loot_id"] = "28795", ["loot_name"] = "Bladespire Warbands", ["prio"] = " Prio: Plate DPS",},
{["loot_id"] = "28796", ["loot_name"] = "Malefic Mask of the Shadows", ["prio"] = " Prio: Melee",},
{["loot_id"] = "28797", ["loot_name"] = "Brute Cloak of the Ogre-Magi", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28800", ["loot_name"] = "Hammer of the Naaru", ["prio"] = " Prio: Ret Pally",},
{["loot_id"] = "28799", ["loot_name"] = "Belt of Divine Inspiration", ["prio"] = " Prio: Caster DPS",},
-----Gruul
{["loot_id"] = "29767", ["loot_name"] = "Leggings of the Fallen Defender", ["prio"] = " Prio: Prot Warrrior = H Priest = Druid (not Kitty)",},
{["loot_id"] = "29766", ["loot_name"] = "Leggings of the Fallen Champion", ["prio"] = " Prio: Pally, Shaman > Rogue",},
{["loot_id"] = "29765", ["loot_name"] = "Leggings of the Fallen Hero", ["prio"] = " Prio: Warlock > Mage > Hunter",},
{["loot_id"] = "28804", ["loot_name"] = "Collar of Cho'gall", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28803", ["loot_name"] = "Cowl of Nature's Breath", ["prio"] = " Prio: R Druid",},
{["loot_id"] = "28822", ["loot_name"] = "Teeth of Gruul", ["prio"] = " Prio: R Druid, H Priest",},
{["loot_id"] = "28823", ["loot_name"] = "Eye of Gruul", ["prio"] = " Prio: R Shaman, H Pally",},
{["loot_id"] = "28824", ["loot_name"] = "Gauntlets of Martial Perfection", ["prio"] = " Prio: Plate DPS",},
{["loot_id"] = "28830", ["loot_name"] = "Dragonspine Trophy", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28827", ["loot_name"] = "Gauntlets of the Dragonslayer", ["prio"] = " Prio: Hunter",},
{["loot_id"] = "28828", ["loot_name"] = "Gronn-Stitched Girdle", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28810", ["loot_name"] = "Windshear Boots", ["prio"] = " Prio: Ele Shaman",},
{["loot_id"] = "28802", ["loot_name"] = "Bloodmaw Magus-Blade", ["prio"] = " Prio: Beast/Frosty then Casters",},
{["loot_id"] = "28825", ["loot_name"] = "Aldori Legacy Defender", ["prio"] = " Prio: Tanks",},
{["loot_id"] = "28794", ["loot_name"] = "Axe of the Gronn Lords", ["prio"] = " Prio: 2H Melee DPS",},
{["loot_id"] = "28826", ["loot_name"] = "Shuriken of Negation", ["prio"] = " Prio: Prot Warrior",},

--  Magtheridon
{["loot_id"] = "29753", ["loot_name"] = "Chestguard of the Fallen Defender", ["prio"] = " Prio: Warrior = Priest = Druid",},
{["loot_id"] = "29755", ["loot_name"] = "Chestguard of the Fallen Hero", ["prio"] = " Prio: Warlock > Mage > Hunter",},
{["loot_id"] = "29754", ["loot_name"] = "Chestguard of the Fallen Champion", ["prio"] = " Prio: Pally > Shaman = Rogue ??",},
{["loot_id"] = "32385", ["loot_name"] = "Magtheridon's Head", ["prio"] = " Prio: Equal",},
{["loot_id"] = "29458", ["loot_name"] = "Aegis of the Vindicator", ["prio"] = " Prio: R Shaman, H Pally",},
{["loot_id"] = "28782", ["loot_name"] = "Crystalheart Pulse-Staff", ["prio"] = " Prio: R Shaman",},
{["loot_id"] = "28789", ["loot_name"] = "Eye of Magtheridon", ["prio"] = " Prio: Caster DPS > S Priest, Ele Shaman, Arcane Mage",},
{["loot_id"] = "28779", ["loot_name"] = "Girdle of the Endless Pit", ["prio"] = " Prio: Plate DPS",},
{["loot_id"] = "28774", ["loot_name"] = "Glaive of the Pit", ["prio"] = " Prio: 2H Melee DPS",},
{["loot_id"] = "28776", ["loot_name"] = "Liar's Tongue Gloves", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28780", ["loot_name"] = "Soul-Eater's Handwraps", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "28778", ["loot_name"] = "Terror Pit Girdle", ["prio"] = " Prio: Physical Mana DPS / DE",},
{["loot_id"] = "28775", ["loot_name"] = "Thundering Greathelm", ["prio"] = " Prio: Plate DPS",},
{["loot_id"] = "28777", ["loot_name"] = "Cloak of the Pit Stalker", ["prio"] = " Prio: Physical DPS",},
{["loot_id"] = "28783", ["loot_name"] = "Eredar Wand of Obliteration", ["prio"] = " Prio: Caster DPS Not S Priest",},
{["loot_id"] = "28781", ["loot_name"] = "Karaborian Talisman", ["prio"] = " Prio: Caster DPS",},
{["loot_id"] = "34845", ["loot_name"] = "Pit Lord's Satchel", ["prio"] = " Prio: None",},
--  Serpentshrine Cavern
-- Trash
{["loot_id"] = "30021", ["loot_name"] = "Wildfury Greatstaff", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30027", ["loot_name"] = "Boots of Courage Unending", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30022", ["loot_name"] = "Pendant of the Perilous", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30620", ["loot_name"] = "Spyglass of the Hidden Fleet", ["prio"] = " Prio: tbd",},
-- Hydross
{["loot_id"] = "30629", ["loot_name"] = "Scarab of Displacement", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30047", ["loot_name"] = "Blackfathom Warbands", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30048", ["loot_name"] = "Brighthelm of Justice", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30052", ["loot_name"] = "Ring of Lethality", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30050", ["loot_name"] = "Boots of the Shifting Nightmare", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30049", ["loot_name"] = "Fathomstone", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32516", ["loot_name"] = "Wraps of Purification", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30664", ["loot_name"] = "Living Root of the Wildheart", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30055", ["loot_name"] = "Shoulderpads of the Stranger", ["prio"] = " Prio: tbd",},
{["loot_id"] = "33055", ["loot_name"] = "Band of Vile Aggression", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30054", ["loot_name"] = "Ranger-General's Chestguard", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30056", ["loot_name"] = "Robe of Hateful Echoes", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30053", ["loot_name"] = "Pauldrons of the Wardancer", ["prio"] = " Prio: tbd",},
-- The Lurker Below
{["loot_id"] = "30061", ["loot_name"] = "Ancestral Ring of Conquest", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30059", ["loot_name"] = "Choker of Animalistic Fury", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30065", ["loot_name"] = "Glowing Breastplate of Truth", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30062", ["loot_name"] = "Grove-Bands of Remulos", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30058", ["loot_name"] = "Mallet of the Tides", ["prio"] = " Prio: tbd",},
{["loot_id"] = "33054", ["loot_name"] = "The Seal of Danzalar", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30064", ["loot_name"] = "Cord of Screaming Terrors", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30060", ["loot_name"] = "Boots of Effortless Striking", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30665", ["loot_name"] = "Earring of Soulful Meditation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30066", ["loot_name"] = "Tempest-Strider Boots", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30067", ["loot_name"] = "Velvet Boots of the Guardian", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30057", ["loot_name"] = "Bracers of Eradication", ["prio"] = " Prio: tbd",},
-- Leotheras
{["loot_id"] = "30240", ["loot_name"] = "Gloves of the Vanquished Defender", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30239", ["loot_name"] = "Gloves of the Vanquished Champion", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30241", ["loot_name"] = "Gloves of the Vanquished Hero", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30097", ["loot_name"] = "Coral-Barbed Shoulderpads", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30095", ["loot_name"] = "Fang of the Leviathan", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30092", ["loot_name"] = "Orca-Hide Boots", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30091", ["loot_name"] = "True-Aim Stalker Bands", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30627", ["loot_name"] = "Tsunami Talisman", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30096", ["loot_name"] = "Girdle of the Invulnerable", ["prio"] = " Prio: tbd",},
-- Karathress
{["loot_id"] = "30246", ["loot_name"] = "Leggings of the Vanquished Defender", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30245", ["loot_name"] = "Leggings of the Vanquished Champion", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30247", ["loot_name"] = "Leggings of the Vanquished Hero", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30101", ["loot_name"] = "Bloodsea Brigand's Vest", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30663", ["loot_name"] = "Fathom-Brooch of the Tidewalker", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30099", ["loot_name"] = "Frayed Tether of the Drowned", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30100", ["loot_name"] = "Soul-Strider Boots", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30626", ["loot_name"] = "Sextant of Unstable Currents", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30090", ["loot_name"] = "World Breaker", ["prio"] = " Prio: tbd",},
-- Morogrim
{["loot_id"] = "33058", ["loot_name"] = "Band of the Vigilant", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30098", ["loot_name"] = "Razor-Scale Battlecloak", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30081", ["loot_name"] = "Warboots of Obliteration", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30085", ["loot_name"] = "Mantle of the Tireless Tracker", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30084", ["loot_name"] = "Pauldrons of the Argent Sentinel", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30083", ["loot_name"] = "Ring of Sundered Souls", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30720", ["loot_name"] = "Serpent-Coil Braid", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30082", ["loot_name"] = "Talon of Azshara", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30075", ["loot_name"] = "Gnarled Chestpiece of the Ancients", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30068", ["loot_name"] = "Girdle of the Tidal Call", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30079", ["loot_name"] = "Illidari Shoulderpads", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30080", ["loot_name"] = "Luminescent Rod of the Naaru", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30008", ["loot_name"] = "Pendant of the Lost Ages", ["prio"] = " Prio: tbd",},
-- Lady Vashj
{["loot_id"] = "30242", ["loot_name"] = "Helm of the Vanquished Champion", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30244", ["loot_name"] = "Helm of the Vanquished Hero", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30243", ["loot_name"] = "Helm of the Vanquished Defender", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30111", ["loot_name"] = "Runetotem's Mantle", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30110", ["loot_name"] = "Coral Band of the Revived", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30112", ["loot_name"] = "Glorious Gauntlets of Crestfall", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30109", ["loot_name"] = "Ring of Endless Coils", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30107", ["loot_name"] = "Vestments of the Sea-Witch", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30106", ["loot_name"] = "Belt of One-Hundred Deaths", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30104", ["loot_name"] = "Cobra-Lash Boots", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30103", ["loot_name"] = "Fang of Vashj", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30102", ["loot_name"] = "Krakken-Heart Breastplate", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30105", ["loot_name"] = "Serpent Spine Longbow", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30108", ["loot_name"] = "Lightfathom Scepter", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30621", ["loot_name"] = "Prism of Inner Calm", ["prio"] = " Prio: tbd",},

--  The Eye
-- Trash
{["loot_id"] = "30030", ["loot_name"] = "Girdle of Fallen Stars", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30026", ["loot_name"] = "Bands of the Celestial Archer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30029", ["loot_name"] = "Bark-Gloves of Ancient Wisdom", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30020", ["loot_name"] = "Fire-Cord of the Magus", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30024", ["loot_name"] = "Mantle of the Elven Kings", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30028", ["loot_name"] = "Seventh Ring of the Tirisfalen", ["prio"] = " Prio: tbd",},
-- Void Reaver
{["loot_id"] = "30248", ["loot_name"] = "Pauldrons of the Vanquished Champion", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30250", ["loot_name"] = "Pauldrons of the Vanquished Hero", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30249", ["loot_name"] = "Pauldrons of the Vanquished Defender", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29984", ["loot_name"] = "Girdle of Zaetar", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32515", ["loot_name"] = "Wristguards of Determination", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30619", ["loot_name"] = "Fel Reaver's Piston", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29983", ["loot_name"] = "Fel-Steel Warhelm", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30450", ["loot_name"] = "Warp-Spring Coil", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29986", ["loot_name"] = "Cowl of the Grand Engineer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29985", ["loot_name"] = "Void Reaver Greaves", ["prio"] = " Prio: tbd",},
-- Al'ar
{["loot_id"] = "29949", ["loot_name"] = "Arcanite Steam-Pistol", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29922", ["loot_name"] = "Band of Al'ar", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29921", ["loot_name"] = "Fire Crest Breastplate", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29947", ["loot_name"] = "Gloves of the Searing Grip", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29918", ["loot_name"] = "Mindstorm Wristbands", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29920", ["loot_name"] = "Phoenix-Ring of Rebirth", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29925", ["loot_name"] = "Phoenix-Wing Cloak", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30447", ["loot_name"] = "Tome of Fiery Redemption", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29924", ["loot_name"] = "Netherbane", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29923", ["loot_name"] = "Talisman of the Sun King", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30448", ["loot_name"] = "Talon of Al'ar", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29948", ["loot_name"] = "Claw of the Phoenix", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32944", ["loot_name"] = "Talon of the Phoenix", ["prio"] = " Prio: tbd",},
-- Solarian
{["loot_id"] = "29950", ["loot_name"] = "Greaves of the Bloodwarder", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29981", ["loot_name"] = "Ethereum Life-Staff", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29965", ["loot_name"] = "Girdle of the Righteous Path", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30449", ["loot_name"] = "Void Star Talisman", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29962", ["loot_name"] = "Heartrazor", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29951", ["loot_name"] = "Star-Strider Boots", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29966", ["loot_name"] = "Vambraces of Ending", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30446", ["loot_name"] = "Solarian's Sapphire", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29977", ["loot_name"] = "Star-Soul Breeches", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32267", ["loot_name"] = "Boots of the Resilient", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29972", ["loot_name"] = "Trousers of the Astromancer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29976", ["loot_name"] = "Worldstorm Gauntlets", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29982", ["loot_name"] = "Wand of the Forgotten Star", ["prio"] = " Prio: tbd",},
-- Kael'thas
{["loot_id"] = "32405", ["loot_name"] = "Verdant Sphere", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30236", ["loot_name"] = "Chestguard of the Vanquished Champion", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30237", ["loot_name"] = "Chestguard of the Vanquished Defender", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30238", ["loot_name"] = "Chestguard of the Vanquished Hero", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29997", ["loot_name"] = "Band of the Ranger-General", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29990", ["loot_name"] = "Crown of the Sun", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29994", ["loot_name"] = "Thalassian Wildercloak", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29987", ["loot_name"] = "Gauntlets of the Sun King", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29995", ["loot_name"] = "Leggings of Murderous Intent", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29996", ["loot_name"] = "Rod of the Sun King", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29992", ["loot_name"] = "Royal Cloak of the Sunstriders", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29991", ["loot_name"] = "Sunhawk Leggings", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29989", ["loot_name"] = "Sunshower Light Cloak", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29988", ["loot_name"] = "The Nexus Key", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29993", ["loot_name"] = "Twinblade of the Phoenix", ["prio"] = " Prio: tbd",},
{["loot_id"] = "29998", ["loot_name"] = "Royal Gauntlets of Silvermoon", ["prio"] = " Prio: tbd",},

--  Hyjal
-- Trash
{["loot_id"] = "32589", ["loot_name"] = "Hellfire-Encased Pendant", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34010", ["loot_name"] = "Pepe's Shroud of Pacification", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32609", ["loot_name"] = "Boots of the Divine Light", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32592", ["loot_name"] = "Chestguard of Relentless Storms", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32591", ["loot_name"] = "Choker of Serrated Blades", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34009", ["loot_name"] = "Hammer of Judgment", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32590", ["loot_name"] = "Nethervoid Cloak", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32946", ["loot_name"] = "Claw of Molten Fury", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32945", ["loot_name"] = "Fist of Molten Fury", ["prio"] = " Prio: tbd",},
-- Winterchill
{["loot_id"] = "30870", ["loot_name"] = "Cuffs of Devastation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30866", ["loot_name"] = "Blood-Stained Pauldrons", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30871", ["loot_name"] = "Bracers of Martyrdom", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30872", ["loot_name"] = "Chronicle of Dark Secrets", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30863", ["loot_name"] = "Deadly Cuffs", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30868", ["loot_name"] = "Rejuvenating Bracers", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30862", ["loot_name"] = "Blessed Adamantite Bracers", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30864", ["loot_name"] = "Bracers of the Pathfinder", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30861", ["loot_name"] = "Furious Shackles", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30865", ["loot_name"] = "Tracker's Blade", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30873", ["loot_name"] = "Stillwater Boots", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30869", ["loot_name"] = "Howling Wind Bracers", ["prio"] = " Prio: tbd",},
-- Anetheron
{["loot_id"] = "30888", ["loot_name"] = "Anetheron's Noose", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30883", ["loot_name"] = "Pillar of Ferocity", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30882", ["loot_name"] = "Bastion of Light", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30881", ["loot_name"] = "Blade of Infamy", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30879", ["loot_name"] = "Don Alejandro's Money Belt", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30886", ["loot_name"] = "Enchanted Leather Sandals", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30878", ["loot_name"] = "Glimmering Steel Mantle", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30874", ["loot_name"] = "The Unbreakable Will", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30885", ["loot_name"] = "Archbishop's Slippers", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30887", ["loot_name"] = "Golden Links of Restoration", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30884", ["loot_name"] = "Hatefury Mantle", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30880", ["loot_name"] = "Quickstrider Moccasins", ["prio"] = " Prio: tbd",},
-- Kaz'rogal
{["loot_id"] = "30915", ["loot_name"] = "Belt of Seething Fury", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30891", ["loot_name"] = "Black Featherlight Boots", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30894", ["loot_name"] = "Blue Suede Shoes", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30918", ["loot_name"] = "Hammer of Atonement", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30916", ["loot_name"] = "Leggings of Channeled Elements", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30895", ["loot_name"] = "Angelista's Sash", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30889", ["loot_name"] = "Kaz'rogal's Hardened Heart", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30917", ["loot_name"] = "Razorfury Mantle", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30919", ["loot_name"] = "Valestalker Girdle", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30892", ["loot_name"] = "Beast-Tamer's Shoulders", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30893", ["loot_name"] = "Sun-Touched Chain Leggings", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30914", ["loot_name"] = "Belt of the Crescent Moon", ["prio"] = " Prio: tbd",},
-- Azgalor
{["loot_id"] = "31093", ["loot_name"] = "Gloves of the Forgotten Vanquisher", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31092", ["loot_name"] = "Gloves of the Forgotten Conqueror", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31094", ["loot_name"] = "Gloves of the Forgotten Protector", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30899", ["loot_name"] = "Don Rodrigo's Poncho", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30901", ["loot_name"] = "Boundless Agony", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30900", ["loot_name"] = "Bow-Stitched Leggings", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30897", ["loot_name"] = "Girdle of Hope", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30896", ["loot_name"] = "Glory of the Defender", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30898", ["loot_name"] = "Shady Dealer's Pantaloons", ["prio"] = " Prio: tbd",},
-- Archimonde
{["loot_id"] = "31096", ["loot_name"] = "Helm of the Forgotten Vanquisher", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31095", ["loot_name"] = "Helm of the Forgotten Protector", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31097", ["loot_name"] = "Helm of the Forgotten Conqueror", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30909", ["loot_name"] = "Antonidas' Aegis of Rapt Concentration", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30908", ["loot_name"] = "Apostle of Argus", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30906", ["loot_name"] = "Bristleblitz Striker", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30902", ["loot_name"] = "Cataclysm's Edge", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30912", ["loot_name"] = "Leggings of Eternity", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30903", ["loot_name"] = "Legguards of Endless Rage", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30907", ["loot_name"] = "Mail of Fevered Pursuit", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30913", ["loot_name"] = "Robes of Rhonin", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30904", ["loot_name"] = "Savior's Grasp", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30911", ["loot_name"] = "Scepter of Purification", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30910", ["loot_name"] = "Tempest of Chaos", ["prio"] = " Prio: tbd",},
{["loot_id"] = "30905", ["loot_name"] = "Midnight Chestguard", ["prio"] = " Prio: tbd",},

--  Black Temple
-- Trash
{["loot_id"] = "32526", ["loot_name"] = "Band of Devastation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32527", ["loot_name"] = "Ring of Ancient Knowledge", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32528", ["loot_name"] = "Blessed Band of Karabor", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32593", ["loot_name"] = "Treads of the Den Mother", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32606", ["loot_name"] = "Girdle of the Lightbearer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32608", ["loot_name"] = "Pillager's Gauntlets", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32943", ["loot_name"] = "Swiftsteel Bludgeon", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34011", ["loot_name"] = "Illidari Runeshield", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34012", ["loot_name"] = "Shroud of the Final Stand", ["prio"] = " Prio: tbd",},
-- Naj'entus
{["loot_id"] = "32234", ["loot_name"] = "Fists of Mukoa", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32240", ["loot_name"] = "Guise of the Tidal Lurker", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32248", ["loot_name"] = "Halberd of Desolation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32238", ["loot_name"] = "Ring of Calming Waves", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32247", ["loot_name"] = "Ring of Captured Storms", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32236", ["loot_name"] = "Rising Tide", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32239", ["loot_name"] = "Slippers of the Seacaller", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32232", ["loot_name"] = "Eternium Shell Bracers", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32377", ["loot_name"] = "Mantle of Darkness", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32237", ["loot_name"] = "The Maelstrom's Fury", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32241", ["loot_name"] = "Helm of Soothing Currents", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32243", ["loot_name"] = "Pearl Inlaid Boots", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32245", ["loot_name"] = "Tide-Stomper's Greaves", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32242", ["loot_name"] = "Boots of Oceanic Fury", ["prio"] = " Prio: tbd",},
-- Supremus
{["loot_id"] = "32261", ["loot_name"] = "Band of the Abyssal Lord", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32262", ["loot_name"] = "Syphon of the Nathrezim", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32251", ["loot_name"] = "Wraps of Precise Flight", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32260", ["loot_name"] = "Choker of Endless Nightmares", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32255", ["loot_name"] = "Felstone Bulwark", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32256", ["loot_name"] = "Waistwrap of Infinity", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32252", ["loot_name"] = "Nether Shadow Tunic", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32250", ["loot_name"] = "Pauldrons of Abyssal Fury", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32254", ["loot_name"] = "The Brutalizer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32253", ["loot_name"] = "Legionkiller", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32258", ["loot_name"] = "Naturalist's Preserving Cinch", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32259", ["loot_name"] = "Bands of the Coming Storm", ["prio"] = " Prio: tbd",},
-- Shade of Akama
{["loot_id"] = "32513", ["loot_name"] = "Wristbands of Divine Influence", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32278", ["loot_name"] = "Grips of Silent Justice", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32266", ["loot_name"] = "Ring of Deceitful Intent", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32270", ["loot_name"] = "Focused Mana Bindings", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32263", ["loot_name"] = "Praetorian's Legguards", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32265", ["loot_name"] = "Shadow-Walker's Cord", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32264", ["loot_name"] = "Shoulders of the Hidden Predator", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32361", ["loot_name"] = "Blind-Seers Icon", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32271", ["loot_name"] = "Kilt of Immortal Nature", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32268", ["loot_name"] = "Myrmidon's Treads", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32273", ["loot_name"] = "Amice of Brilliant Light", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32276", ["loot_name"] = "Flashfire Girdle", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32275", ["loot_name"] = "Spiritwalker Gauntlets", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32279", ["loot_name"] = "The Seeker's Wristguards", ["prio"] = " Prio: tbd",},
-- Teron Gorefiend
{["loot_id"] = "32328", ["loot_name"] = "Botanist's Gloves of Growth", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32329", ["loot_name"] = "Cowl of Benevolence", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32348", ["loot_name"] = "Soul Cleaver", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32512", ["loot_name"] = "Girdle of Lordaeron's Fallen", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32324", ["loot_name"] = "Insidious Bands", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32325", ["loot_name"] = "Rifle of the Stoic Guardian", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32510", ["loot_name"] = "Softstep Boots of Tracking", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32280", ["loot_name"] = "Gauntlets of Enforcement", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32327", ["loot_name"] = "Robe of the Shadow Council", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32323", ["loot_name"] = "Shadowmoon Destroyer's Drape", ["prio"] = " Prio: tbd",},
-- Gurtogg
{["loot_id"] = "32339", ["loot_name"] = "Belt of Primal Majesty", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32501", ["loot_name"] = "Shadowmoon Insignia", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32337", ["loot_name"] = "Shroud of Forgiveness", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32335", ["loot_name"] = "Unstoppable Aggressor's Ring", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32340", ["loot_name"] = "Garments of Temperance", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32333", ["loot_name"] = "Girdle of Stability", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32269", ["loot_name"] = "Messenger of Fate", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32344", ["loot_name"] = "Staff of Immaculate Recovery", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32343", ["loot_name"] = "Wand of Prismatic Focus", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32334", ["loot_name"] = "Vest of Mounting Assault", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32338", ["loot_name"] = "Blood-Cursed Shoulderpads", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32341", ["loot_name"] = "Leggings of Divine Retribution", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32342", ["loot_name"] = "Girdle of Mighty Resolve", ["prio"] = " Prio: tbd",},
-- Reliquary
{["loot_id"] = "32345", ["loot_name"] = "Dreadboots of the Legion", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32350", ["loot_name"] = "Touch of Inspiration", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32353", ["loot_name"] = "Gloves of Unfailing Faith", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32347", ["loot_name"] = "Grips of Damnation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32332", ["loot_name"] = "Torch of the Damned", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32346", ["loot_name"] = "Boneweave Girdle", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32517", ["loot_name"] = "The Wavemender's Mantle", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32354", ["loot_name"] = "Crown of Empowered Fate", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32363", ["loot_name"] = "Naaru-Blessed Life Rod", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32349", ["loot_name"] = "Translucent Spellthread Necklace", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32362", ["loot_name"] = "Pendant of Titans", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32351", ["loot_name"] = "Elunite Empowered Bracers", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32352", ["loot_name"] = "Naturewarden's Treads", ["prio"] = " Prio: tbd",},
-- Shahraz
{["loot_id"] = "31101", ["loot_name"] = "Pauldrons of the Forgotten Conqueror", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31102", ["loot_name"] = "Pauldrons of the Forgotten Vanquisher", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31103", ["loot_name"] = "Pauldrons of the Forgotten Protector", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32365", ["loot_name"] = "Heartshatter Breastplate", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32369", ["loot_name"] = "Blade of Savagery", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32367", ["loot_name"] = "Leggings of Devastation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32370", ["loot_name"] = "Nadina's Pendant of Purity", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32366", ["loot_name"] = "Shadowmaster's Boots", ["prio"] = " Prio: tbd",},
-- Illidary Council
{["loot_id"] = "31100", ["loot_name"] = "Leggings of the Forgotten Protector", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31098", ["loot_name"] = "Leggings of the Forgotten Conqueror", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31099", ["loot_name"] = "Leggings of the Forgotten Vanquisher", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32519", ["loot_name"] = "Belt of Divine Guidance", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32376", ["loot_name"] = "Forest Prowler's Helm", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32331", ["loot_name"] = "Cloak of the Illidari Council", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32373", ["loot_name"] = "Helm of the Illidari Shatterer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32505", ["loot_name"] = "Madness of the Betrayer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32518", ["loot_name"] = "Veil of Turning Leaves", ["prio"] = " Prio: tbd",},
-- Illidan
{["loot_id"] = "32837", ["loot_name"] = "Warglaive of Azzinoth", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32838", ["loot_name"] = "Warglaive of Azzinoth", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31089", ["loot_name"] = "Chestguard of the Forgotten Conqueror", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31091", ["loot_name"] = "Chestguard of the Forgotten Protector", ["prio"] = " Prio: tbd",},
{["loot_id"] = "31090", ["loot_name"] = "Chestguard of the Forgotten Vanquisher", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32374", ["loot_name"] = "Zhar'doom, Greatstaff of the Devourer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32375", ["loot_name"] = "Bulwark of Azzinoth", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32500", ["loot_name"] = "Crystal Spire of Karabor", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32336", ["loot_name"] = "Black Bow of the Betrayer", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32521", ["loot_name"] = "Faceplate of the Impenetrable", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32525", ["loot_name"] = "Cowl of the Illidari High Lord", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32235", ["loot_name"] = "Cursed Vision of Sargeras", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32496", ["loot_name"] = "Memento of Tyrande", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32471", ["loot_name"] = "Shard of Azzinoth", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32524", ["loot_name"] = "Shroud of the Highborne", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32483", ["loot_name"] = "The Skull of Gul'dan", ["prio"] = " Prio: tbd",},
{["loot_id"] = "32497", ["loot_name"] = "Stormrage Signet Ring", ["prio"] = " Prio: tbd",},

--  Sunwell Plateau
-- Trash
{["loot_id"] = "35733", ["loot_name"] = "Ring of Harmonic Beauty", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34351", ["loot_name"] = "Tranquil Majesty Wraps", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34348", ["loot_name"] = "Wand of Cleansing Light", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34183", ["loot_name"] = "Shivering Felspine", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34346", ["loot_name"] = "Mounting Vengeance", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34350", ["loot_name"] = "Gauntlets of the Ancient Shadowmoon", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34347", ["loot_name"] = "Wand of the Demonsoul", ["prio"] = " Prio: tbd",},
-- Kalecgos
{["loot_id"] = "34852", ["loot_name"] = "Bracers of the Forgotten Vanquisher", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34851", ["loot_name"] = "Bracers of the Forgotten Protector", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34848", ["loot_name"] = "Bracers of the Forgotten Conqueror", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34167", ["loot_name"] = "Legplates of the Holy Juggernaut", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34170", ["loot_name"] = "Pantaloons of Calming Strife", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34168", ["loot_name"] = "Starstalker Legguards", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34166", ["loot_name"] = "Band of Lucent Beams", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34169", ["loot_name"] = "Breeches of Natural Aggression", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34165", ["loot_name"] = "Fang of Kalecgos", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34164", ["loot_name"] = "Dragonscale-Encrusted Longblade", ["prio"] = " Prio: tbd",},
-- Brutallus
{["loot_id"] = "34853", ["loot_name"] = "Belt of the Forgotten Conqueror", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34854", ["loot_name"] = "Belt of the Forgotten Protector", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34855", ["loot_name"] = "Belt of the Forgotten Vanquisher", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34177", ["loot_name"] = "Clutch of Demise", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34180", ["loot_name"] = "Felfury Legplates", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34179", ["loot_name"] = "Heart of the Pit", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34181", ["loot_name"] = "Leggings of Calamity", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34176", ["loot_name"] = "Reign of Misery", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34178", ["loot_name"] = "Collar of the Pit Lord", ["prio"] = " Prio: tbd",},
-- Felmyst
{["loot_id"] = "34857", ["loot_name"] = "Boots of the Forgotten Protector", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34856", ["loot_name"] = "Boots of the Forgotten Conqueror", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34858", ["loot_name"] = "Boots of the Forgotten Vanquisher", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34184", ["loot_name"] = "Brooch of the Highborne", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34186", ["loot_name"] = "Chain Links of the Tumultuous Storm", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34185", ["loot_name"] = "Sword Breaker's Bulwark", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34352", ["loot_name"] = "Borderland Fortress Grips", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34182", ["loot_name"] = "Grand Magister's Staff of Torrents", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34188", ["loot_name"] = "Leggings of the Immortal Night", ["prio"] = " Prio: tbd",},
-- Twins
{["loot_id"] = "35290", ["loot_name"] = "Sin'dorei Pendant of Conquest", ["prio"] = " Prio: tbd",},
{["loot_id"] = "35291", ["loot_name"] = "Sin'dorei Pendant of Salvation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "35292", ["loot_name"] = "Sin'dorei Pendant of Triumph", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34206", ["loot_name"] = "Book of Highborne Hymns", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34204", ["loot_name"] = "Amulet of Unfettered Magics", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34189", ["loot_name"] = "Band of Ruinous Delight", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34196", ["loot_name"] = "Golden Bow of Quel'Thalas", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34202", ["loot_name"] = "Shawl of Wonderment", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34193", ["loot_name"] = "Spaulders of the Thalassian Savior", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34210", ["loot_name"] = "Amice of the Convoker", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34199", ["loot_name"] = "Archon's Gavel", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34203", ["loot_name"] = "Grip of Mannoroth", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34194", ["loot_name"] = "Mantle of the Golden Forest", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34195", ["loot_name"] = "Shoulderpads of Vehemence", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34209", ["loot_name"] = "Spaulders of Reclamation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34190", ["loot_name"] = "Crimson Paragon's Cover", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34208", ["loot_name"] = "Equilibrium Epaulets", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34192", ["loot_name"] = "Pauldrons of Perseverance", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34197", ["loot_name"] = "Shiv of Exsanguination", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34205", ["loot_name"] = "Shroud of Redeemed Souls", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34198", ["loot_name"] = "Stanchion of Primal Instinct", ["prio"] = " Prio: tbd",},
-- Mu'ru
{["loot_id"] = "35283", ["loot_name"] = "Sin'dorei Band of Salvation", ["prio"] = " Prio: tbd",},
{["loot_id"] = "35282", ["loot_name"] = "Sin'dorei Band of Dominance", ["prio"] = " Prio: tbd",},
{["loot_id"] = "35284", ["loot_name"] = "Sin'dorei Band of Triumph", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34229", ["loot_name"] = "Garments of Serene Shores", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34240", ["loot_name"] = "Gauntlets of the Soothed Soul", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34211", ["loot_name"] = "Harness of Carnal Instinct", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34214", ["loot_name"] = "Muramasa", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34213", ["loot_name"] = "Ring of Hardened Resolve", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34230", ["loot_name"] = "Ring of Omnipotence", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34233", ["loot_name"] = "Robes of Faltered Light", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34429", ["loot_name"] = "Shifting Naaru Sliver", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34428", ["loot_name"] = "Steely Naaru Sliver", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34231", ["loot_name"] = "Aegis of Angelic Fortune", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34427", ["loot_name"] = "Blackened Naaru Sliver", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34232", ["loot_name"] = "Fel Conqueror Raiments", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34430", ["loot_name"] = "Glimmering Naaru Sliver", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34216", ["loot_name"] = "Heroic Judicator's Chestguard", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34234", ["loot_name"] = "Shadowed Gauntlets of Paroxysm", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34212", ["loot_name"] = "Sunglow Vest", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34228", ["loot_name"] = "Vicious Hawkstrider Hauberk", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34215", ["loot_name"] = "Warharness of Reckless Fury", ["prio"] = " Prio: tbd",},
-- Kil'Jaeden
{["loot_id"] = "34334", ["loot_name"] = "Thori'dal, the Stars' Fury", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34344", ["loot_name"] = "Handguards of Defiled Worlds", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34332", ["loot_name"] = "Cowl of Gul'dan", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34340", ["loot_name"] = "Dark Conjuror's Collar", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34335", ["loot_name"] = "Hammer of Sanctification", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34342", ["loot_name"] = "Handguards of the Dawn", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34336", ["loot_name"] = "Sunflare", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34341", ["loot_name"] = "Borderland Paingrips", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34345", ["loot_name"] = "Crown of Anasterian", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34337", ["loot_name"] = "Golden Staff of the Sin'dorei", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34243", ["loot_name"] = "Helm of Burning Righteousness", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34242", ["loot_name"] = "Tattered Cape of Antonidas", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34343", ["loot_name"] = "Thalassian Ranger Gauntlets", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34241", ["loot_name"] = "Cloak of Unforgivable Sin", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34333", ["loot_name"] = "Coif of Alleria", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34245", ["loot_name"] = "Cover of Ursol the Wise", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34339", ["loot_name"] = "Cowl of Light's Purity", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34329", ["loot_name"] = "Crux of the Apocalypse", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34244", ["loot_name"] = "Duplicitous Guise", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34331", ["loot_name"] = "Hand of the Deceiver", ["prio"] = " Prio: tbd",},
{["loot_id"] = "34247", ["loot_name"] = "Apolyon, the Soul-Render", ["prio"] = " Prio: tbd",},
}
