name: Package Addon

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        env:
           # CF_API_KEY: ${{ secrets.CF_API_KEY }}
           # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
           GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

       - name: Clone project
            uses: actions/checkout@v1

      - name: Package and release for Classic
            uses: BigWigsMods/packager@v1
            with:
              args: -g BCC
